PACKAGE_NAME="pipecam"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="pipecam"
DEST_MODULE_LOCATION[0]="/kernel/drivers/media/usb/pipecam"
MAKE[0]="make KVER=${kernelver} KDIR=/lib/modules/${kernelver}/build"
AUTOINSTALL="yes"
